from __future__ import annotations

NICHE_HASHTAGS: dict[str, tuple[str, ...]] = {
    "fitness": (
        "fitnessjourney",
        "weightlossjourney",
        "fitnesstok",
        "fittok",
        "fitnesscreator",
        "fitnessinfluencer",
        "personaltrainer",
        "gymcoach",
        "nutritioncoach",
        "macroscoach",
        "bodyrecomposition",
        "musclebuilding",
        "strengthtraining",
        "workoutroutine",
        "homeworkout",
        "beginnergymworkout",
        "womensfitness",
        "fitnesstips",
        "fitnessadvice",
        "bodybuildingcoach",
        "calisthenicscoach",
        "pilates",
        "pilatesinstructor",
        "runningcoach",
        "mealprep",
        "nutritiontips",
        "healthyeating",
        "highprotein",
        "macros",
        "weightliftingcoach",
        "mobilitycoach",
        "functionaltraining",
        "strengthandconditioning",
        "girlswholift",
        "womenwholift",
        "trainersoftiktok",
        "bodytransformation",
        "dietitiantok",
        "sportsnutritionist",
        "gymtok",
        "fitnessmotivation",
    ),
    "mom": (
        "momtok",
        "momsoftiktok",
        "momcreator",
        "mominfluencer",
        "momblogger",
        "mompreneur",
        "momcoach",
        "motherhood",
        "sahmlife",
        "workingmom",
        "newmom",
        "firsttimemom",
        "toddlermom",
        "millennialmom",
        "gentleparenting",
        "parentingtips",
        "parentingcoach",
        "postpartum",
        "postpartumjourney",
        "pregnancytok",
        "pregnancycoach",
        "parenttok",
        "momfitness",
        "fitmom",
        "familycontentcreator",
        "momvlog",
        "familyvlog",
        "babyproducts",
        "babyproductreview",
        "amazonmomfinds",
        "momhacks",
        "toddlerlife",
        "momlife",
        "boymom",
        "girlmom",
        "newbornmom",
        "homeschoolmom",
        "singlemom",
        "momsupport",
        "momadvice",
        "momtips",
        "toddleractivities",
        "babyledweaning",
        "breastfeedingmom",
        "momof2",
        "momof3",
        "pregnancyjourney",
    ),
    "lifestyle": (
        "lifestyleblogger",
        "lifestylecreator",
        "lifestyleinfluencer",
        "contentcreator",
        "ugccommunity",
        "ugccreator",
        "microinfluencer",
        "dayinmylife",
        "morningroutine",
        "nightroutine",
        "selfcare",
        "selfcaretips",
        "wellness",
        "wellnesstok",
        "wellnesscoach",
        "wellnesscreator",
        "mindfulness",
        "mindfulnesscoach",
        "healthyhabits",
        "productivitytips",
        "organization",
        "homeorganization",
        "homedecor",
        "amazonfinds",
        "targetfinds",
        "productreview",
        "travelvlog",
        "travelcreator",
        "lifestylecoach",
        "healthcoach",
        "mindsetcoach",
        "holistichealth",
        "holisticwellness",
        "nontoxicliving",
        "cleanliving",
        "intentionalliving",
        "slowliving",
        "minimalistlifestyle",
        "personaldevelopment",
        "growthmindset",
        "habittracking",
        "dailyroutine",
        "balancedlifestyle",
    ),
}


# Free-text phrases for the user-search discovery vector (api.search.users).
# These surface creators that the hashtag feed never shows.
NICHE_SEARCH_TERMS: dict[str, tuple[str, ...]] = {
    "fitness": (
        "fitness coach",
        "personal trainer",
        "online fitness coach",
        "weight loss coach",
        "fat loss coach",
        "fitness nutritionist",
        "nutrition coach",
        "strength coach",
        "pilates instructor",
        "home workout coach",
    ),
    "mom": (
        "mom blogger",
        "mom influencer",
        "mom content creator",
        "mompreneur",
        "motherhood content creator",
        "parenting coach",
        "gentle parenting coach",
        "pregnancy coach",
        "postpartum coach",
    ),
    "lifestyle": (
        "lifestyle blogger",
        "lifestyle influencer",
        "lifestyle content creator",
        "ugc creator",
        "micro influencer",
        "wellness coach",
        "self care creator",
        "morning routine creator",
        "mindfulness coach",
        "product review creator",
    ),
}


# Engagement-bait tags every creator stamps on every video. Harvesting these
# would crawl the generic For You firehose and fill the niche with unrelated
# accounts (this is how a monkey account ended up tagged "mom").
GENERIC_HASHTAGS: frozenset[str] = frozenset(
    {
        "fyp",
        "fypage",
        "fypシ",
        "fypシ゚viral",
        "foryou",
        "foryoupage",
        "fy",
        "viral",
        "viralvideo",
        "viralvideos",
        "viraltiktok",
        "virall",
        "trending",
        "trend",
        "explore",
        "explorepage",
        "xyzbca",
        "tiktok",
        "tiktokviral",
        "tiktokfamous",
        "duet",
        "stitch",
        "greenscreen",
        "capcut",
        "capcutedit",
        "funny",
        "funnyvideos",
        "comedy",
        "meme",
        "memes",
        "lol",
        "relatable",
        "pov",
        "storytime",
        "grwm",
        "ootd",
        "vlog",
        "vlogger",
        "vlogtok",
        "minivlog",
        "ad",
        "ads",
        "sponsored",
        "gifted",
        "commission",
        "asmr",
        "satisfying",
        "oddlysatisfying",
        "aesthetic",
        "cute",
        "love",
        "happy",
        "life",
        "video",
        "videos",
        "new",
        "follow",
        "like",
        "likes",
        "share",
        "real",
        "usa",
        "us",
        "uk",
    }
)


def is_harvestable_hashtag(tag: str) -> bool:
    """Worth feeding into the discovery flywheel: long enough to mean
    something, not generic engagement bait, not just digits."""
    tag = tag.strip().lower()
    return len(tag) >= 3 and not tag.isdigit() and tag not in GENERIC_HASHTAGS


def hashtags_for_niche(niche: str) -> tuple[str, ...]:
    return NICHE_HASHTAGS.get(niche.strip().lower(), ())


def search_terms_for_niche(niche: str) -> tuple[str, ...]:
    return NICHE_SEARCH_TERMS.get(niche.strip().lower(), ())
