from __future__ import annotations

NICHE_HASHTAGS: dict[str, tuple[str, ...]] = {
    "fitness": (
        "fittok",
        "gymtok",
        "fitnesstok",
        "gymlife",
        "gymmotivation",
        "workout",
        "workoutroutine",
        "workoutmotivation",
        "homeworkout",
        "strengthtraining",
        "weightloss",
        "fatloss",
        "musclebuilding",
        "bodybuilding",
        "calisthenics",
        "pilates",
        "yogatiktok",
        "runningtok",
        "mealprep",
        "nutritiontips",
        "personaltrainer",
        "fitnesscoach",
        "beginnergymworkout",
        "fitnessadvice",
    ),
    "mom": (
        "momtok",
        "momlife",
        "momsoftiktok",
        "motherhood",
        "moms",
        "sahm",
        "sahmlife",
        "workingmom",
        "newmom",
        "firsttimemom",
        "postpartum",
        "pregnancytok",
        "parenttok",
        "fitmom",
        "momfitness",
        "momroutine",
        "momvlog",
        "familyvlog",
        "babyproducts",
        "toddlerlife",
        "parentingtips",
        "familytime",
        "toddlermom",
    ),
    "lifestyle": (
        "lifestyle",
        "lifestyleblogger",
        "dayinmylife",
        "dailylife",
        "morningroutine",
        "nightroutine",
        "selfcare",
        "selfcaretips",
        "wellness",
        "wellnesstok",
        "mindfulness",
        "cleangirl",
        "thatgirl",
        "grwm",
        "aesthetic",
        "homedecor",
        "organization",
        "healthyhabits",
        "skincareroutine",
        "fashiontok",
        "travelvlog",
        "productivitytips",
    ),
}


def hashtags_for_niche(niche: str) -> tuple[str, ...]:
    return NICHE_HASHTAGS.get(niche.strip().lower(), ())
